### ISSUE TITLE
Creating a fixture

### ISSUE THREAD

**Issue by alessandrofelder** [UCL-MPHY0021-21-22/RSE-Classwork#22]
## Separating data from code

Your parametrised tests now probably got a bit too big and difficult to read.
Create a `fixture.yaml` file where you can store what you parametrised before
in a more human readable way.

Load the yaml file within the test and use it that structure to feed the parametrize test.

The `fixture.yaml` could look like:
```yaml
- generic:
    time_range_1: ...
    time_range_2: ...
    expected: 
        - ...
        - ...
- no_overlap:
    time_range_1: ...
    time_range_2: ...
    expected: []
```

Once you have a solution, commit it including `Answers https://github.com/UCL-MPHY0021-21-22/RSE-Classwork/issues/22` in the message and push it to your fork on GitHub.

## [Sample solution](https://gist.github.com/alessandrofelder/f3d431964c9cf1a6d4d9c06f821214a9)
